services:
  - type: web
    name: rust-carfagno-enterprises
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NEWS_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 8080
      - key: CORS_ORIGINS
        value: https://rust-carfagno-enterprises.onrender.com
      - key: PYTHONPATH
        value: /app
    healthCheckPath: /health
    autoDeploy: true
